### Get OAuth Token
# @name getToken
POST https://d09d1a89trial.authentication.us10.hana.ondemand.com/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic c2ItMDRhNThlZTMtMzQ2Ni00NGRjLWE1ZTQtOTczYTU3MWJkNzhlIWI2MDcxNDB8eHN1YWEhYjQ5MzkwOjEzOTFjMjZmLTA5ZGItNDg1NS05YTU5LWMxZWY1NDAyOWNmOCRFeklPbF9meU15SnlTYWFuYUZOSDNWNDhaVXpVUWJLQmZwV2stVnlqUDZVPQ==

grant_type=client_credentials

### Get Workflow Definitions
GET https://spa-api-gateway-bpi-us-prod.cfapps.us10.hana.ondemand.com/workflow/rest/v1/workflow-definitions
Authorization: Bearer {{getToken.response.body.access_token}}